version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    container_name: celery_worker
    depends_on:
      - redis
    environment:
      - C_FORCE_ROOT=true

  client:
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: celery_client
    depends_on:
      - worker
