apiVersion: v1
kind: Service
metadata:
  name: ray-head
spec:
  selector:
    app: ray-head
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
    - protocol: TCP
      port: 8265
      targetPort: 8265
  type: LoadBalancer  # Expose dashboard
