apiVersion: apps/v1
kind: Deployment
metadata:
  name: ray-head
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ray-head
  template:
    metadata:
      labels:
        app: ray-head
    spec:
      containers:
        - name: ray-head
          image: rayproject/ray:latest
          args: ["ray", "start", "--head", "--port=6379", "--dashboard-port=8265"]
          ports:
            - containerPort: 6379
            - containerPort: 8265
