version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest  # Use a stable, updated Zookeeper image
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest  # Use a stable, updated Kafka image
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes


  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: kafka_worker
    depends_on:
      - kafka

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: kafka_client
    depends_on:
      - kafka
    command: python producer.py

  producer:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: kafka_producer
    depends_on:
      - kafka
    command: python producer.py